---
title: "leaf_light_project_manual"
author: "cong"
date: "2022/1/17"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Should we mention insect hypothesis or say the nutrients hypothesis.

1.light is important to plants, as resource and information.
light plays a vital role in plants life history, both physiology and ecology.
On the one hand, light as a resource for plants to do photosynthesis; on the other hand, as a circadian information to adjust plant regulation.

2.there are a lot of research on natural light, but few on ALAN.
Light as a traditional ecological factor had catched the attention of Ecologists from antient time (terrestrial habitats, photoinhibition at high intensities; in aquatic habitats; terrestrial plants fits light into sun species and shade species)

3.the fact of negative effect of ALAN to insects.

Hypothesis 
gathering insects increase the soil nutrients(N,P) so that LMA

4.kowning the effect of ALAN to plants is important.(why)


5.what this study does

之前有了一些控制实验 但野外自然条件下的灯光影响还less studied。


## info accumulation
 there are a bunch of research showing that man-made light could cast negative effects to human, animals and environment. But few focus on the effect of globally strengthening artificial night lighting to plants. 


## the outline of introduction
#light pollution around the world  generally to animals(), plants(), humen(), and ecosystem().

Ecological light pollution refers to a type of
light pollution that alters natural light
regimes in terrestrial and aquatic ecosystems
[44]. For example Verheijen (1985) [45]
have proposed the term “photopollution” to
mean “artificial light having diverse effects
on wildlife”, but as this literally means
“light pollution” more describing term like
“ecological light pollution” is needed to
describe the impact of light to ecosystems.

ALAN is ennough to motivate plants physiological changes.



#ALAN drives insects decline 


#hardly focus on ALAN's effect to plants 


#so based on that what we want to do

 
 #the relationship between plant and light 
## light is important for plant 
light is one kind of necessary resource and signal which  affecting plants physiologically and ecologically. Plants use light as a resource to do photosynthesis, and also light cycle is one of the key factors to induce many plant behaviors like growing, flowering, hibernation or dormancy.

(light plays a vital role in plants life history, both physiology and ecology.On the one hand, light as a resource for plants to do photosynthesis; on the other hand, as a circadian information to adjust plant regulation.)
 
 
## the ecological impacts of nighttime light pollution : a mechanistic appraisal

Light affects organisms via the visual system in animals, the photosynthetic system in plants, and through various non-visual pigments in both plants and animals.

The balance
between hours of light and of darkness constrains the time
available for these processes and so changes in the availability
of both light and darkness as a resource can have positive
or negative effects on an organism, dependent on whether
it is the presence or absence of light that poses the greater
constraint.



## light pollutionis a driver of insect declines
artificial light at night(ALAN)

around the 1950s, light traps became popular among
entomologists for use in surveying insect biodiversity (Leather, 2015).

While the total fitness impact of an artificial light
source will depend on its intensity, direction, spectral distribution
(Elvidge et al., 2010), and flicker rate (Inger et al., 2014), as well as the
time of day and structure of nearby surfaces (Horváth et al., 2009; Szaz
et al., 2015), the light output of most common fixtures is more than
enough to radically disturb the entire habitat of small-bodied animals
such as insects.

A growing body of research demonstrates that ALAN can impact the
fitness of plants and animals (Bennie et al., 2016; Gaston et al., 2013),

some suggest that one 
third of insects attracted to stationary artificial light sources die before
morning, either through exhaustion or predation (Eisenbeis, 2006;
Frank, 2006; Yoon et al., 2010);










