---
title: "llp_structure"
author: "Cong"
date: "2022/3/2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# INTRODUCTION

先写它则个
What is ALAN? Introduction of ALAN.

With the development of technology, the night sky is brighter than ever before both at city and in natural place, which known as light pollution.
Habitats could be effected directly near artificial light at night(ALAN) and indirectly by sky glow scattered from ALAN.

Light as a traditional ecological factor had catched the attention of Ecologists from antient time, such as terrestrial plants fits light into sun species and shade species and shows photoinhibition at high intensities.
However, not enough attention had been paid to the artificial light at night(ALAN), which had been demonstrated suffices to impact the fitness of plants and animals.(Rich and Longcore, 2006;Singhal et al., 2019)

*What is ALAN? Introduction of ALAN.*
Light as a traditional ecological factor had caught the attention of Ecologists since ancient time, while nowadays artificial light at night as one kind of emerging man-made factor should also link up to our consideration.
Artificial light at night(ALAN), comprises artificial light sources emission and diffuse sky glow, had disturbed natural daily and seasonal cycles of light since the start of 20th century.( Cinzano, Falchi & Elvidge 2001)
So far, artificial light at night extends both intensity covered a large illuminance range from very little to almost daylight and extent covered 23% of the World's terrestrial surfaces between
75°N and 60°S.(Bennie et al. 2016,Falchi et al. 2016)
Ignoring the effect of artificial light at night to multilevel ecological processes doesn't make sense any more, hence came a series of study on ALAN.


*ALAN studies (effects of ALAN)*
Artificial light at night calls effects among wild taxonomic groups both zoology and botany, from mammals, birds, reptiles and amphibians, fishes, invertebrates and plants etc.(Rich and Longcore, 2006)
Typically, lighted towers and glow of city lights confuse migrating birds, and streetlight attracting sea turtle hatchlings which dead parched. 
Recently study shows ALAN is an important bringer to drive insects population decline.(Boyes et al., 2021;Owens et al., 2020).
while not too much studies on ALAN' effect to plants.
Biomass responses of widely and less‐widely naturalized alien plants to artificial light at night
(Speißer et al., 2021)

(no rigorous studies have examined effects of artificial night lighting on plants in conditions approaching their natural environment.
A lack of clear evidence for such effects, however, should not lead one to conclude that no effects exist or that any particular effects that may be noticed are either beneficial, deleterious, or of no consequence to the plant.)

*Effects of ALAN on leaf traits* (including your expectation) (soil N up -> LMA decrease) (nutrient and LMA)
Photoreceptors familys
ALAN prolong the light time to plants, so comes with more photosynthesis time and more products)
ALAN disturb plants photoperiod so LMA will decrease)
Most of LMA consists of carbon and water, 
We expect that ...



Effect of (day)light (LMA increase) *light and LMA*

Objectives
a) ALAN indirectly gathering insects increase the soil nutrients(N,P) so that LMA
b) ALAN directly increases LMA (same as daylight


In this study we set light experiment and choose two species representing sun species and shade species respectively on understory in man-made rubber tree forest.















1.light is important to plants, as resource and information.

light plays a vital role in plants life history, both physiologically and ecologically.
On the one hand, light as a resource for plants to do photosynthesis; on the other hand, as a circadian information to adjust plant regulation.


2.there are a lot of research on natural light, but few on ALAN.

Light as a traditional ecological factor had catched the attention of Ecologists from antient time, such as terrestrial plants fits light into sun species and shade species and shows photoinhibition at high intensities.
With the development of modern technology, light sources and lamp types abound which lightening the night far more bright both in city ecolosystem and suburb regime.
However, not enough attention had been paid to the artificial light at night(ALAN), which had been demonstrated suffices to impact the fitness of plants and animals.(Rich and Longcore, 2006;Singhal et al., 2019)


3.until now research on the effect of ALAN to plants and insects
Such as, ALAN is an important bringer to drive insects population decline  (Boyes et al., 2021;Owens et al., 2020).
Biomass responses of widely and less‐widely naturalized alien plants to artificial light at night
(Speißer et al., 2021)


4.the general pattern ALAN to plants still unknown and the importance konwing it.

fully the extent of these impacts requires conceptual models that can (i) characterize the highly
heterogeneous nature of the night-time light environment at a scale relevant to plant physiology; and
(ii) scale physiological responses to predict impacts at the level of the whole plant, population, community
and ecosystem.)
The Matthew effect: Common species become more common and rare ones become more rare in response to artificial light at night
(Bennie et al., 2016;Liu et al. 2022)

based on 3&4 comes our Hypothesis 
1)ALAN directly effect plants biomass
2)ALAN indirectly gathering insects increase the soil nutrients(N,P) so that LMA

5.So in this study we set a wild light experiment and choose two species representing sun species and shade species respectively on understory.



# MATERIALS AND METHODS

*Plot location*

XTBG 
RP2 NEW 0M	592M	N21°54'36.05''	E101°16'29.23''
RP5 0M	601M	N21°54'26.02''	E101°16'22.66''

*Species*

Melastoma candidum D. Don
Colocasia gigantea (Blume) Hook. f.
(avoiding the nitrogen fix plants like Leguminosae; evergreen)

*Light information*

LED (10w, BiWeiZhaoMing)
1.2 m from the ground. 
battery (12v/30Ah)

*experiment time*

start from 2019 November until 2021 November.

*measurement*

Canopy openness 
equipment: Nikon COOLPIX4500 with a fish-eye lens(Nikon FC-E8)
picture manipulation: R package(LeafArea Katabuchi,2015)

Distance 
tape measure

LMA
punch leaf disc
leaf disc method

*data analysis*

Bayesian Linear Mixed Model 
rstan 

**experimental setup**

The field experiment is located within the Xishuangbanna Tropical Botanical Garden(XTBG),China in rubber tree forest(N21°54' E101°16') where we totally set 5 plots.
LED (10w) is used to create an artificial light environment in all plots at night. The LED system includes 6 components. 
A metal box with an opening is used as a rainproof protector which is attached to a tree at around 1.2 m from the ground. 
A rechargeable lithium battery (12v/30Ah) and an electric timer controls the timing and duration of the LED light operation at night.
An electric wire was used to connect battery and LED which was hanging from a tree branch with a lampshade at approximately 2 m from the ground. 

Considering the understory condition (individual numbers, distribution of individuals) and specific species(it should be evergreen species,also avoiding the nitrogen fix plants like Leguminosae) of each plot, finally two species respectively in two plots were chosen for our study , Gigantea (Blume) Hook. f. representing shade species and (Melastoma candidum D. Don) for sun species.
This experiment started from 2019 November, and samples were catched on 2021 November.

**Measurements**

We measured the horizontal distance and geographic orientation of each individual away from the LED using tape measure representing the relative light strength.
Canopy openness was selected to be on behalf of day light, which photographed by Nikon COOLPIX4500 with fish-eye lens(Nikon FC-e8) then measured using R package "LeafArea"(Katabuchi, 2015).
For leaf mass per area(LMA), we use leaf disc(10mm^2) punched from leaf avoiding vein and leaf margin instead of whole-leaf to calculate LMA value.


**Data Analysis**

To analyze the effects of ALAN, daylight's effect, and their interaction on both **Melastoma candidum D. Don** and **Colocasia gigantea (Blume) Hook. f.**.
We fitted a Bayesian linear mixed-effets model using 'rstan' package() in R().
Leaf mass per area(LMA) of each leaf of each individual was the response variable.
Distance from the ALAN of each individual was transformed by log then reciprocal, which make sense for both the accumulation of insects and the intensity of ALAN fade away from distance.
We conducted individual as a random effect for each species on our model, for the non-independence of individuals of the same species.


                                                                   
Bayesian linear mixed model
individual as random effect



# RESULT
For species Melastoma candidum D. Don, no specific effects of ALAN has been found(95% confidence interval of coefficients covers zero, Table.1)
For Colocasia gigantea (Blume) Hook. f. both ALAN's effect and daylight's effect are significant (95% confidence interval doesn't cover zero)
We found no significant interaction between ALAN's effect and daylight's effect shows no significance.
While we can see the effect coefficients show the same trend for both species, which ALAN causes a negative effect on LMA.




# DISCUSSION
specific species should add to the consider of ALAN effects.
Different type of plants may have different responses.

more experiment and modeling are needed to further research.

(quantify the full-time plant light intercepts can be considered in the future study)


